# Generated by Django 3.1.2 on 2020-10-29 15:59

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cadastro_paciente', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=32)),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('slug', models.SlugField(unique=True)),
                ('altura', models.PositiveIntegerField()),
                ('peso', models.DecimalField(decimal_places=2, max_digits=8)),
                ('imc', models.DecimalField(decimal_places=2, max_digits=8)),
                ('peso_ideal', models.DecimalField(decimal_places=2, max_digits=8)),
                ('braco_relaxado_direito', models.DecimalField(decimal_places=2, max_digits=8)),
                ('braco_relaxado_esquerdo', models.DecimalField(decimal_places=2, max_digits=8)),
                ('braco_contraido_direito', models.DecimalField(decimal_places=2, max_digits=8)),
                ('braco_contraido_esquerdo', models.DecimalField(decimal_places=2, max_digits=8)),
                ('antebraco_direito', models.DecimalField(decimal_places=2, max_digits=8)),
                ('antebraco_esquerdo', models.DecimalField(decimal_places=2, max_digits=8)),
                ('punho_direito', models.DecimalField(decimal_places=2, max_digits=8)),
                ('punho_esquerdo', models.DecimalField(decimal_places=2, max_digits=8)),
                ('panturrilha_direita', models.DecimalField(decimal_places=2, max_digits=8)),
                ('panturrilha_esquerda', models.DecimalField(decimal_places=2, max_digits=8)),
                ('coxa_direita', models.DecimalField(decimal_places=2, max_digits=8)),
                ('coxa_esquerda', models.DecimalField(decimal_places=2, max_digits=8)),
                ('coxa_proximal_direita', models.DecimalField(decimal_places=2, max_digits=8)),
                ('coxa_proximal_esquerda', models.DecimalField(decimal_places=2, max_digits=8)),
                ('pescoco', models.DecimalField(decimal_places=2, max_digits=8)),
                ('ombro', models.DecimalField(decimal_places=2, max_digits=8)),
                ('cintura', models.DecimalField(decimal_places=2, max_digits=8)),
                ('abdomen', models.DecimalField(decimal_places=2, max_digits=8)),
                ('quadril', models.DecimalField(decimal_places=2, max_digits=8)),
                ('biceps', models.DecimalField(decimal_places=2, max_digits=8)),
                ('abdominal', models.DecimalField(decimal_places=2, max_digits=8)),
                ('triceps', models.DecimalField(decimal_places=2, max_digits=8)),
                ('suprailiaca', models.DecimalField(decimal_places=2, max_digits=8)),
                ('subescapula', models.DecimalField(decimal_places=2, max_digits=8)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastro_paciente.cadastropaciente')),
            ],
            managers=[
                ('objetos', django.db.models.manager.Manager()),
            ],
        ),
    ]
